### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by bilderbuchi** [jamesrhester/Lerche.jl#1]
Hi! 
This is very much a drive-by comment, but "Lerchen" is not German for "lark", but for "larks", as it is plural. "Lerche" is the singular, "lark".

**Comment by jamesrhester** [comment]
A very important drive-by comment.  My bad because I had a couple of German speakers in the building that I failed to ask. I'll think about whether a rename or fixing the spiel is better.

**Comment by bilderbuchi** [comment]
Hehe. Well I thought while I don't speak enough Julia to contribute, at least I can be useful as a native speaker, and I guess a rename is easier *before* having significant adoption.

**Comment by jamesrhester** [comment]
OK, the rename has now taken place and I'll try to figure out how to fix the Julia registry.

**Comment by jamesrhester** [comment]
All done.
