### ISSUE TITLE
`_get_lexer_callbacks` not defined

### ISSUE THREAD

**Issue by guyvdbroeck** [jamesrhester/Lerche.jl#12]
Running a local copy of https://github.com/jamesrhester/Lerche.jl/blob/master/examples/calc.jl gives an error:
```
julia> include("calc.jl")
ERROR: LoadError: UndefVarError: _get_lexer_callbacks not defined
Stacktrace:
 [1] Lark(grammar::String, loptions::Dict{String, Any}, source::String, cache_file::String)
   @ Lerche ~/.julia/packages/Lerche/rO9vr/src/lark.jl:190
 [2] Lark(grammar::String; options::Base.Iterators.Pairs{Symbol, Any, Tuple{Symbol, Symbol}, NamedTuple{(:parser, :transformer), Tuple{String, CalculateTree}}})
   @ Lerche ~/.julia/packages/Lerche/rO9vr/src/lark.jl:121
 [3] top-level scope
   @ ~/.julia/dev/LogicCircuits/scratch/calc.jl:49
 [4] include(fname::String)
   @ Base.MainInclude ./client.jl:444
 [5] top-level scope
   @ REPL[3]:1
```

**Comment by jamesrhester** [comment]
Thanks for the bug report. which led me to a TODO statement. Currently transformations on the lexed string are not available. That means that a call to `Lark` that sets the `transformer` option causes an error. I will see if I can find a quick fix.

**Comment by guyvdbroeck** [comment]
Is there a performance cost to doing the transformation after parsing?

**Comment by erezsh** [comment]
@jamesrhester You can make `Lerche.parse()` do the transform, and in later versions embed it into the parse-tree-builder. The users don't have to know about it. (just my two cents)

**Comment by jamesrhester** [comment]
@guyvdbroeck the performance cost that I can see is a trade-off between traversing the parse tree a second time (a cost) but having a known type for the parse tree during parsing if no transformer is run during parse tree construction (a benefit).  I'm thinking about ways in which this could be made more Julian, perhaps by providing a type parameter that fixes the output type of the transformer methods.

**Comment by jamesrhester** [comment]
@erezsh Yes that would fix it - the `transform` method is simply called as soon as parsing is complete.

**Comment by jamesrhester** [comment]
Commit 8872eb2 contains a fix for the `include(calc.jl)` issue. It simply transforms using the specified transformer following construction of the parse tree as suggested [above](https://github.com/jamesrhester/Lerche.jl/issues/12#issuecomment-822134190). I'll issue a new release.
